#!/bin/bash
set -v

rm -f /mnt/scratch/glbrooks/BETTER_TEST_ENVIRONMENTS/BETTER_EVAL_PHASE2_HITL/app/results.json
rm -f /mnt/scratch/glbrooks/BETTER_TEST_ENVIRONMENTS/BETTER_EVAL_PHASE2_HITL/app/test_data.bp.json

cp /mnt/scratch/glbrooks/BETTER_TEST_ENVIRONMENTS/BETTER_EVAL_PHASE2_HITL/app/TEST-ir-HITL-eval-tasks.json /mnt/scratch/glbrooks/BETTER_TEST_ENVIRONMENTS/BETTER_EVAL_PHASE2_HITL/app/ir-tasks.json
cp /mnt/scratch/glbrooks/BETTER_TEST_ENVIRONMENTS/BETTER_EVAL_PHASE2_HITL/app/TEST-tasks-HITL.json /mnt/scratch/glbrooks/BETTER_TEST_ENVIRONMENTS/BETTER_EVAL_PHASE2_HITL/app/tasks.json

docker pull gregorybrooks/tasks-runner:3.1.1

docker pull gregorybrooks/better-query-builder-ngram:3.0.1

docker pull gregorybrooks/better-query-builder-1:3.0.0

docker pull gregorybrooks/better-reranker-z1:3.2.0

